### ISSUE TITLE
Dependency on SQLite is incompatible with AWS Amplify

### ISSUE THREAD

**Issue by ristkof** [mergesort/Bodega#16]
Bodega has an explicit version number dependency:

```
.package(url: "https://github.com/stephencelis/SQLite.swift.git", exact: Version(0, 13, 3)),
```

and [Amplify](https://github.com/aws-amplify/amplify-swift) has an explicit dependency:

```
.package(url: "https://github.com/stephencelis/SQLite.swift.git", exact: "0.13.2"),
```

which makes them incompatible, and now I need to have both in my project.

Any way to change this on Bodega's side? On the side of AWS this is a known issue: https://github.com/aws-amplify/amplify-swift/issues/2592

**Comment by mergesort** [comment]
Hey @ristkof! I spent the day thinking about this and consulting with a few other open source maintainers and came to the conclusion that I should make the change you're requesting in Bodega. I was initially hesitant to unpin the library from a specific version for likely the same reasons the Amplify maintainers pin their library to a specific version, ease of maintenance, but in the context of people using many open source libraries with differing requirements I shouldn't enforce this kind of requirement.

I'm going to work on a few Boutique and Bodega related features over the next couple of days and will make sure to include this. If you'd like to expedite it you're free to submit a pull request that bumps the version to at least 0.13.2.

That would be going into Bodega's Package.swift and replacing this line
```.package(url: "https://github.com/stephencelis/SQLite.swift.git", exact: Version(0, 13, 3))```
With
```.package(url: "https://github.com/stephencelis/SQLite.swift.git", from: Version(0, 13, 2))```

If you do this please make sure to run Bodega's tests, and to try the Boutique [Demo](https://github.com/mergesort/Boutique/tree/main/Demo) and [Performance Profiler](https://github.com/mergesort/Boutique/tree/main/Performance%20Profiler) projects to make sure they all still work fine. I do remember there were some issues with earlier versions of SQLite.swift, I wonder if that's what the Amplify maintainers ran into as well.

Thanks a lot for bringing this to my attention, and hopefully the upgrade goes smoothly.

**Comment by androoo** [comment]
Ive been on the Amplify discord all day trying to find a path forward on this same issue. Happy to see this has been raised here and has a solution in mind. Any idea of when this will be updated?

**Comment by mergesort** [comment]
Hi folks, so sorry I've had a really busy last couple of months and lost track of this issue. Last night I pushed up [a commit](https://github.com/mergesort/Bodega/commit/822f97e977f508b4461500a5baa0ceedd02f87ad) that removes exact pinning, instead starting from 0.13.2. I'll make a more formal release soon when I have some free time, but in the mean time you can point your project to Bodega's `main` branch in SPM to unblock you.

Thanks for being patient, and appreciate the nudge!

**Comment by mergesort** [comment]
Hey folks, I wanted to check and see if everything worked now? If so I'll close out this issue.

**Comment by androoo** [comment]
It does indeed. Thank you so much, greatly appreciated!

**Comment by mergesort** [comment]
Terrific, glad to hear that!

**Comment by mergesort** [comment]
I apologize that this took so long to turn into a formal release but the last few months I've had some other obligations that took priority over Boutique and Bodega work.

As of [version 2.1.0](https://github.com/mergesort/Bodega/releases/tag/2.1.0) Bodega officially pins SQLite.swift to any version of SQLite.swift greater than 0.13.2, so if you were pointing your dependencies to the `main` branch you can now point it to the 2.1.0 release.
