### ISSUE TITLE
vacuum sqlite database after removing all data

### ISSUE THREAD

**Issue by mikakruschel** [mergesort/Bodega#28]
I noticed that even after calling `removeAllData`, the size of the sqlite3 file doesn't shrink. This is because sqlite reserves the freed space for future use. To compact the database file and reduce disk space, we can use the [VACUUM](https://www.sqlite.org/lang_vacuum.html) command. 

I think it may not be necessary to vacuum the database after every remove command, but it would make sense to call it after `removeAllData`. 

More information about vacuuming can be found at https://blog.eidinger.info/keep-your-coredata-store-small-by-vacuuming#heading-what-is-vacuum. 

Let me know if you think it's a good idea, and I'll open a PR.

**Comment by mergesort** [comment]
That's a great catch @mikakrusche, I hadn't noticed that behavior in Bodega. I think it's a great idea to address and would definitely welcome a PR. Thank you so much! 🙇🏻‍♂️
